# Generated by Django 3.0.4 on 2020-03-27 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=120)),
                ('task_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('task_due_datetime', models.DateTimeField(default=None)),
                ('task_status', models.CharField(choices=[('ACT', 'Active'), ('HOL', 'On hold'), ('COM', 'Completed')], default='ACT', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
